language: node_js
node_js:
  - "7"
script:
 - echo "Deploy!!"
install:
  - npm install
  - npm run build
  - npm install -g firebase-tools
after_success:
  - firebase deploy --project portfolio-app-5ad6d --token 1//0gLwNzn8NHD73CgYIARAAGBASNwF-L9IrcdLp67ARHfPm013WB8ygPLMozosKk4fZwB3KZ67-M4R5wolIpAsUwU4KPOenf1DBx58